// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.wss.springboot.libserver;

public final class Greeter {
  private Greeter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wss_springboot_libserver_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wss_springboot_libserver_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_wss_springboot_libserver_Greeting_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_wss_springboot_libserver_Greeting_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgreeter.proto\022\034com.wss.springboot.libs" +
      "erver\"/\n\006Person\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tl" +
      "ast_name\030\002 \001(\t\"\033\n\010Greeting\022\017\n\007message\030\001 " +
      "\001(\t2m\n\021HelloWorldService\022X\n\010sayHello\022$.c" +
      "om.wss.springboot.libserver.Person\032&.com" +
      ".wss.springboot.libserver.GreetingB\005P\001\210\001" +
      "\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_wss_springboot_libserver_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_wss_springboot_libserver_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wss_springboot_libserver_Person_descriptor,
        new java.lang.String[] { "FirstName", "LastName", });
    internal_static_com_wss_springboot_libserver_Greeting_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_wss_springboot_libserver_Greeting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_wss_springboot_libserver_Greeting_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
