// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: greeter.proto

package com.wss.springboot.libserver;

/**
 * <pre>
 **
 * 声明接口
 * </pre>
 *
 * Protobuf service {@code com.wss.springboot.libserver.HelloWorldService}
 */
public  abstract class HelloWorldService
    implements com.google.protobuf.Service {
  protected HelloWorldService() {}

  public interface Interface {
    /**
     * <code>rpc sayHello(.com.wss.springboot.libserver.Person) returns (.com.wss.springboot.libserver.Greeting);</code>
     */
    public abstract void sayHello(
        com.google.protobuf.RpcController controller,
        com.wss.springboot.libserver.Person request,
        com.google.protobuf.RpcCallback<com.wss.springboot.libserver.Greeting> done);

  }

  public static com.google.protobuf.Service newReflectiveService(
      final Interface impl) {
    return new HelloWorldService() {
      @java.lang.Override
      public  void sayHello(
          com.google.protobuf.RpcController controller,
          com.wss.springboot.libserver.Person request,
          com.google.protobuf.RpcCallback<com.wss.springboot.libserver.Greeting> done) {
        impl.sayHello(controller, request, done);
      }

    };
  }

  public static com.google.protobuf.BlockingService
      newReflectiveBlockingService(final BlockingInterface impl) {
    return new com.google.protobuf.BlockingService() {
      public final com.google.protobuf.Descriptors.ServiceDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }

      public final com.google.protobuf.Message callBlockingMethod(
          com.google.protobuf.Descriptors.MethodDescriptor method,
          com.google.protobuf.RpcController controller,
          com.google.protobuf.Message request)
          throws com.google.protobuf.ServiceException {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.callBlockingMethod() given method descriptor for " +
            "wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return impl.sayHello(controller, (com.wss.springboot.libserver.Person)request);
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getRequestPrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getRequestPrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.wss.springboot.libserver.Person.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

      public final com.google.protobuf.Message
          getResponsePrototype(
          com.google.protobuf.Descriptors.MethodDescriptor method) {
        if (method.getService() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "Service.getResponsePrototype() given method " +
            "descriptor for wrong service type.");
        }
        switch(method.getIndex()) {
          case 0:
            return com.wss.springboot.libserver.Greeting.getDefaultInstance();
          default:
            throw new java.lang.AssertionError("Can't get here.");
        }
      }

    };
  }

  /**
   * <code>rpc sayHello(.com.wss.springboot.libserver.Person) returns (.com.wss.springboot.libserver.Greeting);</code>
   */
  public abstract void sayHello(
      com.google.protobuf.RpcController controller,
      com.wss.springboot.libserver.Person request,
      com.google.protobuf.RpcCallback<com.wss.springboot.libserver.Greeting> done);

  public static final
      com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptor() {
    return com.wss.springboot.libserver.Greeter.getDescriptor().getServices().get(0);
  }
  public final com.google.protobuf.Descriptors.ServiceDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }

  public final void callMethod(
      com.google.protobuf.Descriptors.MethodDescriptor method,
      com.google.protobuf.RpcController controller,
      com.google.protobuf.Message request,
      com.google.protobuf.RpcCallback<
        com.google.protobuf.Message> done) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.callMethod() given method descriptor for wrong " +
        "service type.");
    }
    switch(method.getIndex()) {
      case 0:
        this.sayHello(controller, (com.wss.springboot.libserver.Person)request,
          com.google.protobuf.RpcUtil.<com.wss.springboot.libserver.Greeting>specializeCallback(
            done));
        return;
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getRequestPrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getRequestPrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.wss.springboot.libserver.Person.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public final com.google.protobuf.Message
      getResponsePrototype(
      com.google.protobuf.Descriptors.MethodDescriptor method) {
    if (method.getService() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "Service.getResponsePrototype() given method " +
        "descriptor for wrong service type.");
    }
    switch(method.getIndex()) {
      case 0:
        return com.wss.springboot.libserver.Greeting.getDefaultInstance();
      default:
        throw new java.lang.AssertionError("Can't get here.");
    }
  }

  public static Stub newStub(
      com.google.protobuf.RpcChannel channel) {
    return new Stub(channel);
  }

  public static final class Stub extends com.wss.springboot.libserver.HelloWorldService implements Interface {
    private Stub(com.google.protobuf.RpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.RpcChannel channel;

    public com.google.protobuf.RpcChannel getChannel() {
      return channel;
    }

    @Override
    public  void sayHello(
        com.google.protobuf.RpcController controller,
        com.wss.springboot.libserver.Person request,
        com.google.protobuf.RpcCallback<com.wss.springboot.libserver.Greeting> done) {
      channel.callMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.wss.springboot.libserver.Greeting.getDefaultInstance(),
        com.google.protobuf.RpcUtil.generalizeCallback(
          done,
          com.wss.springboot.libserver.Greeting.class,
          com.wss.springboot.libserver.Greeting.getDefaultInstance()));
    }
  }

  public static BlockingInterface newBlockingStub(
      com.google.protobuf.BlockingRpcChannel channel) {
    return new BlockingStub(channel);
  }

  public interface BlockingInterface {
    public com.wss.springboot.libserver.Greeting sayHello(
        com.google.protobuf.RpcController controller,
        com.wss.springboot.libserver.Person request)
        throws com.google.protobuf.ServiceException;
  }

  private static final class BlockingStub implements BlockingInterface {
    private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
      this.channel = channel;
    }

    private final com.google.protobuf.BlockingRpcChannel channel;

    public com.wss.springboot.libserver.Greeting sayHello(
        com.google.protobuf.RpcController controller,
        com.wss.springboot.libserver.Person request)
        throws com.google.protobuf.ServiceException {
      return (com.wss.springboot.libserver.Greeting) channel.callBlockingMethod(
        getDescriptor().getMethods().get(0),
        controller,
        request,
        com.wss.springboot.libserver.Greeting.getDefaultInstance());
    }

  }

  // @@protoc_insertion_point(class_scope:com.wss.springboot.libserver.HelloWorldService)
}

